### ISSUE TITLE
vr200 crashes

### ISSUE THREAD

**Issue by aski71** [Eisbaeeer/ioBroker.vr200#22]
Hi,
I'm running Node 16. Since then I have issues with vr200 adapter crashes.
Today I received the message that vr200 is built for an older node version and iobroker tried to rebuild, but failed:
Any help? Thanks.

vr200.0 | 2022-02-23 09:18:03.822 | info | starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.vr200, node: v16.14.0, js-controller: 4.0.15
-- | -- | -- | --
host.homie | 2022-02-23 09:17:51.310 | info | instance system.adapter.vr200.0 started with pid 24165
host.homie | 2022-02-23 09:17:50.745 | info | iobroker npm-rebuild: exit 1
host.homie | 2022-02-23 09:17:49.661 | error | iobroker npm-rebuild: Rebuilding native modules failed
host.homie | 2022-02-23 09:16:57.427 | info | iobroker npm-rebuild: Rebuilding native modules ...
host.homie | 2022-02-23 09:16:54.153 | info | iobroker rebuild
host.homie | 2022-02-23 09:16:54.152 | warn | adapter "vr200" seems to be installed for a different version of Node.js. Trying to rebuild it... 1 attempt
host.homie | 2022-02-23 09:16:54.149 | info | system.adapter.vr200.0 will be rebuilt
host.homie | 2022-02-23 09:16:54.148 | info | Adapter system.adapter.vr200.0 needs rebuild and will be restarted afterwards.
host.homie | 2022-02-23 09:16:54.147 | error | instance system.adapter.vr200.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.homie | 2022-02-23 09:16:54.146 | error | Caught by controller[0]: }
host.homie | 2022-02-23 09:16:54.145 | error | Caught by controller[0]: ]
host.homie | 2022-02-23 09:16:54.145 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.vr200/main.js'
host.homie | 2022-02-23 09:16:54.144 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.vr200/lib/utils.js',
host.homie | 2022-02-23 09:16:54.143 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js',
host.homie | 2022-02-23 09:16:54.141 | error | Caught by controller[0]: '/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/index.js',
host.homie | 2022-02-23 09:16:54.139 | error | Caught by controller[0]: '/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js',
host.homie | 2022-02-23 09:16:54.137 | error | Caught by controller[0]: '/opt/iobroker/node_modules/@iobroker/js-controller-common/index.js',
host.homie | 2022-02-23 09:16:54.136 | error | Caught by controller[0]: '/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/logger.js',
host.homie | 2022-02-23 09:16:54.134 | error | Caught by controller[0]: '/opt/iobroker/node_modules/winston-daily-rotate-file/index.js',
host.homie | 2022-02-23 09:16:54.132 | error | Caught by controller[0]: '/opt/iobroker/node_modules/winston-daily-rotate-file/daily-rotate-file.js',
host.homie | 2022-02-23 09:16:54.131 | error | Caught by controller[0]: '/opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js',
host.homie | 2022-02-23 09:16:54.129 | error | Caught by controller[0]: requireStack: [
host.homie | 2022-02-23 09:16:54.127 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.homie | 2022-02-23 09:16:54.125 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1005:19) {
host.homie | 2022-02-23 09:16:54.124 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
host.homie | 2022-02-23 09:16:54.122 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:981:32)
host.homie | 2022-02-23 09:16:54.120 | error | Caught by controller[0]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
host.homie | 2022-02-23 09:16:54.119 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1103:14)
host.homie | 2022-02-23 09:16:54.117 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js:15:14)
host.homie | 2022-02-23 09:16:54.115 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:102:18)
host.homie | 2022-02-23 09:16:54.113 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1005:19)
host.homie | 2022-02-23 09:16:54.111 | error | Caught by controller[0]: at Function.Module._load (node:internal/modules/cjs/loader:778:27)
host.homie | 2022-02-23 09:16:54.109 | error | Caught by controller[0]: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
host.homie | 2022-02-23 09:16:54.107 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.vr200/main.js
host.homie | 2022-02-23 09:16:54.075 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.vr200/lib/utils.js
host.homie | 2022-02-23 09:16:54.074 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js
host.homie | 2022-02-23 09:16:54.072 | error | Caught by controller[0]: - /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/index.js
host.homie | 2022-02-23 09:16:54.071 | error | Caught by controller[0]: - /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js
host.homie | 2022-02-23 09:16:54.069 | error | Caught by controller[0]: - /opt/iobroker/node_modules/@iobroker/js-controller-common/index.js
host.homie | 2022-02-23 09:16:54.064 | error | Caught by controller[0]: - /opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/logger.js
host.homie | 2022-02-23 09:16:54.062 | error | Caught by controller[0]: - /opt/iobroker/node_modules/winston-daily-rotate-file/index.js
host.homie | 2022-02-23 09:16:54.059 | error | Caught by controller[0]: - /opt/iobroker/node_modules/winston-daily-rotate-file/daily-rotate-file.js
host.homie | 2022-02-23 09:16:54.048 | error | Caught by controller[0]: - /opt/iobroker/node_modules/file-stream-rotator/FileStreamRotator.js
host.homie | 2022-02-23 09:16:54.045 | error | Caught by controller[0]: Require stack:
host.homie | 2022-02-23 09:16:54.043 | error | Caught by controller[0]: Error: Cannot find module 'moment'
host.homie | 2022-02-23 09:16:54.041 | error | Caught by controller[0]: ^
host.homie | 2022-02-23 09:16:54.039 | error | Caught by controller[0]: throw e;
host.homie | 2022-02-23 09:16:54.033 | error | Caught by controller[0]: /opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/logger.js:237
host.homie | 2022-02-23 09:16:50.958 | info | instance system.adapter.vr200.0 started with pid 22293
host.homie | 2022-02-23 09:16:20.868 | info | Restart adapter system.adapter.vr200.0 because enabled
host.homie | 2022-02-23 09:16:20.858 | error | instance system.adapter.vr200.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
vr200.0 | 2022-02-23 09:16:20.042 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
vr200.0 | 2022-02-23 09:16:20.040 | info | terminating
vr200.0 | 2022-02-23 09:16:20.035 | error | Exception-Code: ENOENT: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/node-kobold/lib/cert/neatocloud.com.crt'
vr200.0 | 2022-02-23 09:16:20.034 | error | Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/node-kobold/lib/cert/neatocloud.com.crt' at Object.openSync (node:fs:585:3) at Object.readFileSync (node:fs:453:35) at Object.request (/opt/iobroker/node_modules/node-kobold/lib/api.js:33:20) at doAction (/opt/iobroker/node_modules/node-kobold/lib/robot.js:321:13) at Robot.getState (/opt/iobroker/node_modules/node-kobold/lib/robot.js:30:5) at updateRobot (/opt/iobroker/node_modules/iobroker.vr200/main.js:635:11) at Timeout.update [as _onTimeout] (/opt/iobroker/node_modules/iobroker.vr200/main.js:592:9) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
vr200.0 | 2022-02-23 09:16:20.013 | error | uncaught exception: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/node-kobold/lib/cert/neatocloud.com.crt'

**Comment by Eisbaeeer** [comment]
Did you solved the issue?
